INSERT INTO employee (first_name, last_name, role_id) VALUES ('Carla', 'Forsythe', 1)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('Rick', 'Claiborne', 2)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('Anita', 'Nguyen', 3)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('Beverly', 'Martinez', 4)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('Amanda', 'Clarke', 5)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('David', 'Lucas', 6)
INSERT INTO employee (first_name, last_name, role_id) VALUES ('Marques', 'Donnely', 7)

INSERT INTO role (title, salary, department_id) VALUES ('Sales Lead', 80000, 1)
INSERT INTO role (title, salary, department_id) VALUES ('Salesperson', 75000, 1)
INSERT INTO role (title, salary, department_id) VALUES ('Lead Engineer', 120000, 2)
INSERT INTO role (title, salary, department_id) VALUES ('Software Engineer', 110000, 2)
INSERT INTO role (title, salary, department_id) VALUES ('Account Manager', 100000, 3)
INSERT INTO role (title, salary, department_id) VALUES ('Accountant', 90000, 3)
INSERT INTO role (title, salary, department_id) VALUES ('Lawyer', 150000, 4)